output_indices = [ 0 ]

[[nodes]]
bias = 9.131854331629723

  [[nodes.connections]]
  index = 1
  weight = -7.202912026493101

  [[nodes.connections]]
  index = 4
  weight = 4.184099353566256

  [[nodes.connections]]
  index = 0
  weight = -7.266626654328718

  [[nodes.connections]]
  index = 5
  weight = 0.005440437924967512

[[nodes]]
bias = -3.9326028548376124

  [[nodes.connections]]
  index = 3
  weight = 6.699214767849661

  [[nodes.connections]]
  index = 2
  weight = 3.082891148752197

  [[nodes.connections]]
  index = 1
  weight = 1.0891250821507825

  [[nodes.connections]]
  index = 5
  weight = 2.7868686329476335

  [[nodes.connections]]
  index = 4
  weight = -2.7581729473132794

[[nodes]]
bias = 1.9769106131609286

  [[nodes.connections]]
  index = 2
  weight = 0.4168809960236703

  [[nodes.connections]]
  index = 4
  weight = 8.684933430246701

  [[nodes.connections]]
  index = 0
  weight = -5.907382034175189

  [[nodes.connections]]
  index = 3
  weight = -9.64192045097644

  [[nodes.connections]]
  index = 1
  weight = 4.938529908197139

  [[nodes.connections]]
  index = 5
  weight = -8.231639085046583

[[nodes]]
bias = -5.9219121730023385

  [[nodes.connections]]
  index = 3
  weight = 3.2701281215252114

  [[nodes.connections]]
  index = 5
  weight = -4.304501610015612

  [[nodes.connections]]
  index = 1
  weight = -4.275216790794831

  [[nodes.connections]]
  index = 4
  weight = 0.12533792540202535

  [[nodes.connections]]
  index = 0
  weight = -0.012302834078761218
